version: '2.3'
services:
  kemono-nginx:
    image: nginx
    container_name: kemono-nginx
    depends_on:
      kemono-app-dev:
        condition: service_healthy
      kemono-archiver:
        condition: service_started
    ports:
      - 5000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - data-dev:/storage
  kemono-app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: kemono
    restart: unless-stopped
    depends_on:
      kemono-db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
      - KEMONO_SITE=http://localhost:5000
      - PGUSER=nano
      - PGPASSWORD=shinonome
      - PGDATABASE=kemonodb
      - PGHOST=kemono-db
      - REDIS_HOST=kemono-redis
      - REDIS_PORT=6379
      - ARCHIVERHOST=kemono-archiver
      - ARCHIVERPORT=80
    volumes:
      - .:/app
      - frontend-assets-dev:/app/dist:ro
      - data-dev:/storage
    sysctls:
      net.core.somaxconn: 500
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 1m
      timeout: 2m
      retries: 3
      start_period: 30s
  kemono-frontend-dev:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: kemono-frontend-dev
    environment:
      - NODE_ENV=development
      - KEMONO_SITE=http://localhost:5000
    volumes:
      # quick hack to allow webpack config updates between reups
      - ./client/webpack.config.js:/app/webpack.config.js
      - ./client/webpack.dev.js:/app/webpack.dev.js
      - ./client/src:/app/src
      - ./client/static:/app/static
      # and another one for misc configs
      - ./client/configs:/app/configs
      - frontend-assets-dev:/app/dev
    stdin_open: true
  kemono-db:
    image: healthcheck/postgres
    container_name: kemono-db
    environment:
      - POSTGRES_USER=nano
      - POSTGRES_PASSWORD=shinonome
      - POSTGRES_DB=kemonodb
    volumes:
      - db-data-dev:/var/lib/postgresql/data/
    restart: unless-stopped
    # ports:
    #  - 5432:5432
  kemono-archiver:
    build:
      context: ./archiver
      dockerfile: Dockerfile.dev
    container_name: kemono-archiver
    restart: unless-stopped
    depends_on:
      kemono-db:
        condition: service_healthy
    environment:
      - FLASK_ENV=development
    volumes:
      - ./archiver:/app
      - ./kitsune.py:/app/config.py
      - data-dev:/storage
    sysctls:
      net.core.somaxconn: 40000
  kemono-redis:
    image: redis:6.2.0
    container_name: kemono-redis
  autoheal:
    restart: always
    container_name: kemono-autoheal
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  # If you need to store your volumes manually, uncomment the "driver_opts" lines and specify your "device" location.
  db-data-dev:
    driver: local
    # driver_opts:
    #   type: 'none'
    #   o: 'bind'
    #   device: "/mnt/slab1/kemono-db-dev"
  data-dev:
    driver: local
    # driver_opts:
    #   type: 'none'
    #   o: 'bind'
    #   device: "/mnt/slab1/kemono-dev"
  frontend-assets-dev:
    driver: local
    # driver_opts:
    #   type: 'none'
    #   o: 'bind'
    #   device: "/mnt/slab1/kemono-assets-dev"
