version: '2.3'
services:
  kemono-nginx:
    image: nginx
    container_name: kemono-nginx
    depends_on:
      kemono-app:
        condition: service_healthy
      kemono-archiver:
        condition: service_started
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - data:/storage
  kemono-db:
    image: groonga/pgroonga:2.3.3-alpine-13-slim
    container_name: kemono-db
    environment:
      - POSTGRES_USER=nano
      - POSTGRES_PASSWORD=shinonome
      - POSTGRES_DB=kemonodb
    volumes:
      - db-data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "-c", "pg_isready -U nano -d kemonodb"]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  kemono-app:
    build:
      context: ..
      dockerfile: ./Dockerfile
    container_name: kemono
    restart: unless-stopped
    depends_on:
      kemono-db:
        condition: service_healthy
    volumes:
      - frontend-assets:/app/dist:ro
    sysctls:
      net.core.somaxconn: 500
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 1m
      timeout: 2m
      retries: 3
      start_period: 30s
  kemono-frontend:
    build:
      context: ../client
      dockerfile: ../client/Dockerfile
    container_name: kemono-frontend
    environment:
      - NODE_ENV=production
    volumes:
      - frontend-assets:/app/dist
  kemono-archiver:
    build:
      context: ../archiver
      dockerfile: ../archiver/Dockerfile
    container_name: kemono-archiver
    restart: unless-stopped
    depends_on:
      kemono-db:
        condition: service_healthy
    environment:
      - FLASK_ENV=production
    volumes:
      - ./kitsune.py:/app/config.py
      - ./redis_map.py:/app/redis_map.py
      - data:/storage
    sysctls:
      net.core.somaxconn: 40000
  autoheal:
    restart: always
    container_name: kemono-autoheal
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kemono-redis:
    image: redis:6.2.0
    container_name: kemono-redis
volumes:
  # If you need to store your volumes manually, uncomment the "driver_opts" lines and specify your "device" location.
  db-data:
    driver: local
    # driver_opts:
    #   type: 'none'
    #   o: 'bind'
    #   device: "/mnt/slab1/kemono-db"
  data:
    driver: local
    # driver_opts:
    #   type: 'none'
    #   o: 'bind'
    #   device: "/mnt/slab1/kemono"
  frontend-assets:
    driver: local
    # driver_opts:
    #   type: 'none'
    #   o: 'bind'
    #   device: "/mnt/slab1/kemono-assets"
